{
 "title": "Scorecard Dashboard",
 "time": { "from": "now-1y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "province_id",
    "label": "Province",
    "query": "select name_km AS __text, code AS __value  from locations where parent_id is null;"
   },
   {
    "name": "year",
    "label": "Year",
    "query": "select distinct(year) from scorecards where program_id in (${program_id})"
   },
   {
    "name": "facility_name",
    "label": "Sector",
    "query": "select name_en from facilities where parent_id is not null AND program_id in (${program_id});"
   },
   {
    "name": "facility_id",
    "label": "Sector",
    "query": "select id AS __value  from facilities where parent_id is not null AND name_en in ($facility_name) AND program_id in (${program_id});"
   },
   {
    "name": "scorecard_type",
    "label": "Scorecard Type",
    "query": "Self-Assessment : 1,Community Scorecard : 2 "
   },
   {
    "name": "age",
    "label": "Age",
    "query": "< 15 : 0 AND 14, 15 - 30 : 15 AND 30, 31 - 45 : 31 AND 45,  > 45 : 46 AND 99"
   },
   {
    "name": "gender",
    "label": "Gender",
    "query": "Male : male, Female : female, Other : other"
   },
   {
    "name": "profile",
    "label": "Profile",
    "query": "Disability, Minority, ID Poor, Youth"
   },
   {
    "name": "program_id",
    "label": "Program",
    "query": "select name AS __text, id AS __value from programs order by id;"
   },
   {
    "name": "local_ngo_name",
    "label": "Local NGO",
    "query": "select name from local_ngos where program_id in (${program_id});"
   },
   {
    "name": "local_ngo_id",
    "label": "Local NGO",
    "query": "select id AS __value  from local_ngos where name in ($local_ngo_name) AND program_id in (${program_id});"
   }
  ]
 },
 "panels": [
  {
   "title": "ផែនទីអនុវត្តប័ណ្ណដាក់ពិន្ទុឌីជីថល",
   "type": "alexandra-trackmap-panel",
   "gridPos": { "h": 17, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "WITH _conducted_scorecards AS (\n  SELECT *\n  FROM\n    (\n      SELECT\n        s.*,\n        concat_ws (\n          ', ',\n          (CASE WHEN s.number_of_disability > 0 THEN 'Disability' END),\n          (CASE WHEN s.number_of_ethnic_minority > 0 THEN 'Minority' END),\n          (CASE WHEN s.number_of_youth > 0 THEN 'Youth' END),\n          (CASE WHEN s.number_of_id_poor > 0 THEN 'ID Poor' END),\n          (CASE WHEN (s.number_of_disability = 0 AND s.number_of_ethnic_minority = 0 AND s.number_of_youth = 0 AND s.number_of_id_poor = 0) THEN 'N/A' END)\n        ) as profile\n      FROM scorecards as s\n      INNER JOIN participants as p on s.id::varchar(20) = p.scorecard_uuid\n      WHERE \n        s.program_id in (${program_id})\n        AND $__timeFilter(s.conducted_date)\n        AND s.scorecard_type in ($scorecard_type)\n        AND s.year in ($year)\n        AND s.facility_id in ($facility_id)\n        AND s.local_ngo_id in ($local_ngo_id)\n        AND s.deleted_at is null\n        AND s.locked_at is not null\n        AND p.age BETWEEN ${age:raw}\n        AND p.gender in ($gender)\n      group by s.id\n    ) as sc\n  WHERE string_to_array(sc.profile, ', ') && array[$profile]\n)\n\nSELECT \n  CONCAT(\n    'អង្គការអនុវត្តប័ណ្ណដាក់ពិន្ទុ (', locations.name_km, ')', \n    '<ol>',\n    ARRAY_TO_STRING(array_agg(DISTINCT CONCAT('<li><a href=\"', local_ngos.website_url ,'\" target=\"_blank\">', local_ngos.name, '</a></li>')),''),\n    '</ol>',\n    '<p>',\n    'ប័ណ្ណដាក់ពិន្ទុ(បានអនុវត្ត:<b>',\n    (SELECT COUNT(*) FROM _conducted_scorecards WHERE province_id = locations.code),\n    '</b> / បានគ្រោងទុក:<b>', COUNT(*), '</b>)',\n    '</p>'\n  ) as popup,\n\n  locations.osm_latitude as latitude, \n  locations.osm_longitude as longitude,\n\n  CONCAT_WS('/', (SELECT COUNT(*) FROM _conducted_scorecards WHERE province_id = locations.code), COUNT(*)) as tooltip\n\nFROM scorecards \nINNER JOIN locations ON scorecards.province_id = locations.code\nINNER JOIN local_ngos ON scorecards.local_ngo_id = local_ngos.id\nWHERE \n  scorecards.program_id in (${program_id})\n  AND $__timeFilter(scorecards.created_at)\n  AND scorecards.scorecard_type in ($scorecard_type) \n  AND scorecards.year in ($year) \n  AND scorecards.facility_id in ($facility_id)\n  AND scorecards.province_id in ($province_id)\n  AND scorecards.local_ngo_id in ($local_ngo_id)\n  AND scorecards.deleted_at is null\nGROUP BY \n  locations.name_km, locations.code, locations.latitude, locations.longitude;"
    }
   ]
  },
  {
   "title": "សង្ខេបប័ណ្ណដាក់ពិន្ទុ",
   "type": "yesoreyeram-boomtheme-panel",
   "gridPos": { "h": 1, "w": 3, "x": 15, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  created_at AS \"time\",\n  latitude\nFROM locations\nWHERE\n  $__timeFilter(created_at)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "ប័ណ្ណដាក់ពិន្ទុសរុប (អនុវត្តរួចរាល់/គ្រោងទុក)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 15, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH _scorecards AS (\n  SELECT \n    s.*,\n    concat_ws (\n      ', ',\n      (CASE WHEN s.number_of_disability > 0 THEN 'Disability' END),\n      (CASE WHEN s.number_of_ethnic_minority > 0 THEN 'Minority' END),\n      (CASE WHEN s.number_of_youth > 0 THEN 'Youth' END),\n      (CASE WHEN s.number_of_id_poor > 0 THEN 'ID Poor' END),\n      (CASE WHEN (s.number_of_disability = 0 AND s.number_of_ethnic_minority = 0 AND s.number_of_youth = 0 AND s.number_of_id_poor = 0) THEN 'N/A' END)\n    ) as profile\n  FROM scorecards as s\n  INNER JOIN participants as p on s.id::varchar(20) = p.scorecard_uuid\n  WHERE \n    s.program_id in (${program_id})\n    AND $__timeFilter(s.conducted_date)\n    AND s.scorecard_type in ($scorecard_type) \n    AND s.year in ($year) \n    AND s.facility_id in ($facility_id)\n    AND s.province_id in ($province_id)\n    AND s.local_ngo_id in ($local_ngo_id)\n    AND s.deleted_at is null\n    AND s.locked_at is not null\n    AND p.age BETWEEN ${age:raw}\n    AND p.gender in ($gender)\n  GROUP BY s.id\n),\ntotal_conducted AS (\n  SELECT count(*) as \"Total Conducted\"\n  from _scorecards as sc\n  where string_to_array(sc.profile, ', ') && array[$profile]\n),\ntotal_planned AS (\n  SELECT\n    count(*) as \"Total Planned\"\n  FROM scorecards AS s\n  WHERE\n    s.program_id in (${program_id})\n    AND $__timeFilter(s.created_at)\n    AND s.scorecard_type in ($scorecard_type) \n    AND s.year in ($year) \n    AND s.facility_id in ($facility_id)\n    AND s.province_id in ($province_id)\n    AND s.local_ngo_id in ($local_ngo_id)\n    AND s.deleted_at is null\n)\n\nSELECT \n  concat_ws (\n    ' / ',\n    (select * from total_conducted),\n    (select * from total_planned)  \n  )"
    }
   ]
  },
  {
   "title": "រយៈពេលអនុវត្តប័ណ្ណដាក់ពិន្ទុ (កាលបរិច្ឆេទចាប់ផ្តើមដល់បញ្ចប់)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 15, "x": 9, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH _scorecards AS (\n  SELECT \n    s.*,\n    EXTRACT(epoch FROM (s.locked_at - s.conducted_date))/86400 as implemented_time,\n    concat_ws (\n      ', ',\n      (CASE WHEN s.number_of_disability > 0 THEN 'Disability' END),\n      (CASE WHEN s.number_of_ethnic_minority > 0 THEN 'Minority' END),\n      (CASE WHEN s.number_of_youth > 0 THEN 'Youth' END),\n      (CASE WHEN s.number_of_id_poor > 0 THEN 'ID Poor' END),\n      (CASE WHEN (s.number_of_disability = 0 AND s.number_of_ethnic_minority = 0 AND s.number_of_youth = 0 AND s.number_of_id_poor = 0) THEN 'N/A' END)\n    ) as profile\n  FROM scorecards as s\n  INNER JOIN participants as p on s.id::varchar(20) = p.scorecard_uuid\n  WHERE \n    s.program_id in (${program_id})\n    AND $__timeFilter(s.conducted_date)\n    AND s.scorecard_type in ($scorecard_type) \n    AND s.year in ($year) \n    AND s.facility_id in ($facility_id)\n    AND s.province_id in ($province_id)\n    AND s.local_ngo_id in ($local_ngo_id)\n    AND s.deleted_at is null\n    AND s.locked_at is not null\n    AND p.age BETWEEN ${age:raw}\n    AND p.gender in ($gender)\n  group by s.id\n),\nfiltered_scorecards AS (\n  SELECT \n  (\n    CASE WHEN implemented_time <= (ceil(implemented_time) - 0.5) THEN ceil(implemented_time) - 0.5\n         ELSE ceil(implemented_time)\n    END\n  ) as duration\n  FROM _scorecards\n  WHERE string_to_array(profile, ', ') && array[$profile]\n)\n\nSELECT\n  min(duration)::integer AS \"អប្បបរមា (ថ្ងៃ)\",\n  avg(duration)::integer AS \"មធ្យម (ថ្ងៃ)\",\n  max(duration)::integer AS \"អតិបរមា (ថ្ងៃ)\"\nFROM filtered_scorecards;"
    }
   ]
  },
  {
   "title": "ប័ណ្ណដាក់ពិន្ទុដែលអនុវត្តរួចរាល់តាមសេវា",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 7, "x": 9, "y": 9 },
   "targets": [
    {
     "rawSql": "WITH _scorecards AS (\n  SELECT \n    s.*,\n    concat_ws (\n      ', ',\n      (CASE WHEN s.number_of_disability > 0 THEN 'Disability' END),\n      (CASE WHEN s.number_of_ethnic_minority > 0 THEN 'Minority' END),\n      (CASE WHEN s.number_of_youth > 0 THEN 'Youth' END),\n      (CASE WHEN s.number_of_id_poor > 0 THEN 'ID Poor' END),\n      (CASE WHEN (s.number_of_disability = 0 AND s.number_of_ethnic_minority = 0 AND s.number_of_youth = 0 AND s.number_of_id_poor = 0) THEN 'N/A' END)\n    ) as profile\n  FROM scorecards as s\n  INNER JOIN participants as p on s.id::varchar(20) = p.scorecard_uuid\n  WHERE \n    s.program_id in (${program_id})\n    AND $__timeFilter(s.conducted_date)\n    AND s.scorecard_type in ($scorecard_type) \n    AND s.year in ($year) \n    AND s.facility_id in ($facility_id)\n    AND s.province_id in ($province_id)\n    AND s.local_ngo_id in ($local_ngo_id)\n    AND s.deleted_at is null\n    AND s.locked_at is not null\n    AND p.age BETWEEN ${age:raw}\n    AND p.gender in ($gender)\n  GROUP BY s.id\n)\n\nSELECT \n  facilities.name_km as name, \n  COUNT(CASE WHEN t.scorecard_type = 1 THEN 1 END) as \"វាយតម្លៃខ្លួនឯង\",\n  COUNT(CASE WHEN t.scorecard_type = 2 THEN 2 END) as \"ប័ណ្ណដាក់ពិន្ទុសហគមន៍\"\nFROM (\n  SELECT * \n  FROM _scorecards as sc\n  WHERE string_to_array(sc.profile, ', ') && array[$profile]\n) as t\nINNER JOIN facilities ON t.facility_id = facilities.id\nGROUP BY facilities.name_km;"
    }
   ]
  },
  {
   "title": "ប័ណ្ណដាក់ពិន្ទុដែលអនុវត្តរួចរាល់សរុបធ្វើឡើងតាមប្រភេទវិស័យ",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH _scorecards AS (\n  SELECT \n    s.*,\n    concat_ws (\n      ', ',\n      (CASE WHEN s.number_of_disability > 0 THEN 'Disability' END),\n      (CASE WHEN s.number_of_ethnic_minority > 0 THEN 'Minority' END),\n      (CASE WHEN s.number_of_youth > 0 THEN 'Youth' END),\n      (CASE WHEN s.number_of_id_poor > 0 THEN 'ID Poor' END),\n      (CASE WHEN (s.number_of_disability = 0 AND s.number_of_ethnic_minority = 0 AND s.number_of_youth = 0 AND s.number_of_id_poor = 0) THEN 'N/A' END)\n    ) as profile\n  FROM scorecards as s\n  INNER JOIN participants as p on s.id::varchar(20) = p.scorecard_uuid\n  WHERE \n    s.program_id in (${program_id})\n    AND $__timeFilter(s.conducted_date)\n    AND s.scorecard_type in ($scorecard_type) \n    AND s.year in ($year) \n    AND s.facility_id in ($facility_id)\n    AND s.province_id in ($province_id)\n    AND s.local_ngo_id in ($local_ngo_id)\n    AND s.deleted_at is null\n    AND s.locked_at is not null\n    AND p.age BETWEEN ${age:raw}\n    AND p.gender in ($gender)\n  GROUP BY s.id\n)\n\nSELECT \n  facilities.name_km as name, \n  COUNT(*)\nFROM (\n  SELECT * \n  FROM _scorecards\n  WHERE string_to_array(_scorecards.profile, ', ') && array[$profile]\n) as t\nINNER JOIN facilities ON t.facility_id = facilities.id\nGROUP BY facilities.name_km;"
    }
   ]
  },
  {
   "title": "ប្រជាជនចូលរួមបែងចែកតាមភេទ",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH pa AS (\n  SELECT\n    p.*,\n    (\n      CASE \n        WHEN gender = 'male' THEN 'ប្រុស'\n        WHEN gender = 'female' THEN 'ស្រី'\n        ELSE 'ផ្សេងៗ'\n      END\n    ) as gender_km,\n    concat_ws (\n      ', ',\n      (CASE WHEN p.disability = true THEN 'Disability' END),\n      (CASE WHEN p.minority = true THEN 'Minority' END),\n      (CASE WHEN p.youth = true THEN 'Youth' END),\n      (CASE WHEN p.poor_card = true THEN 'ID Poor' END),\n      (CASE WHEN (p.disability = false AND p.minority = false AND p.youth = false AND p.poor_card = false) THEN 'N/A' END)\n    ) as profile\n  FROM participants AS p\n)\n\nSELECT\n  gender_km,\n  count(*)\nFROM pa\nINNER JOIN scorecards ON \n  pa.scorecard_uuid = scorecards.id::varchar(255)\nWHERE \n  scorecards.program_id in (${program_id})\n  AND $__timeFilter(scorecards.conducted_date)\n  AND scorecards.facility_id in ($facility_id)\n  AND scorecards.year in ($year)\n  AND scorecards.scorecard_type in ($scorecard_type)\n  AND scorecards.province_id in ($province_id)\n  AND scorecards.local_ngo_id in ($local_ngo_id)\n  AND scorecards.deleted_at is null\n  AND pa.gender in ($gender)\n  AND pa.age BETWEEN ${age:raw}\n  AND string_to_array(pa.profile, ', ') && array[$profile]\nGROUP BY gender_km\nORDER BY 1"
    }
   ]
  },
  {
   "title": "ប្រជាជនចូលរួមបែងចែកតាមលក្ខណៈសម្បតិ្ត",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH par AS (\n  (\n    SELECT participants.*, 'ID Poor' as profile, 'ប័ណ្ណក្រីក្រ' as profile_km\n    FROM participants WHERE participants.poor_card is true\n  )\n  UNION ALL\n  (\n    SELECT participants.*, 'Disability' as profile, 'ពិការភាព' as profile_km\n    FROM participants WHERE participants.disability is true\n  )\n  UNION ALL\n  (\n    SELECT participants.*, 'Minority' as profile, 'ជនជាតិភាគតិច' as profile_km\n    FROM participants WHERE participants.minority is true\n  )\n  UNION ALL\n  (\n    SELECT participants.*, 'Youth' as profile, 'យុវជន' as profile_km\n    FROM participants WHERE participants.youth is true\n  )\n)\n\nSELECT \n  par.profile_km, count(*)\nFROM par\nINNER JOIN scorecards ON par.scorecard_uuid = scorecards.id::varchar(255)\nWHERE \n  scorecards.program_id in (${program_id})\n  AND $__timeFilter(scorecards.conducted_date)\n  AND scorecards.facility_id in ($facility_id)\n  AND scorecards.year in ($year)\n  AND scorecards.scorecard_type in ($scorecard_type)\n  AND scorecards.province_id in ($province_id)\n  AND scorecards.local_ngo_id in ($local_ngo_id)\n  AND scorecards.deleted_at is null\n  AND par.gender in ($gender)\n  AND par.age BETWEEN ${age:raw}\n  AND par.profile in ($profile)\nGROUP BY par.profile_km"
    }
   ]
  },
  {
   "title": "ប័ណ្ណដាក់ពិន្ទុសរុប (អនុវត្តរួចរាល់ vs គ្រោងទុក) តាមវិស័យ",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "targets": [
    {
     "rawSql": "WITH filtered_scorecards AS (\n  SELECT *\n  FROM\n    (\n      SELECT\n        s.*,\n        concat_ws (\n          ', ',\n          (CASE WHEN s.number_of_disability > 0 THEN 'Disability' END),\n          (CASE WHEN s.number_of_ethnic_minority > 0 THEN 'Minority' END),\n          (CASE WHEN s.number_of_youth > 0 THEN 'Youth' END),\n          (CASE WHEN s.number_of_id_poor > 0 THEN 'ID Poor' END),\n          (CASE WHEN (s.number_of_disability = 0 AND s.number_of_ethnic_minority = 0 AND s.number_of_youth = 0 AND s.number_of_id_poor = 0) THEN 'N/A' END)\n        ) as profile\n      FROM scorecards as s\n      INNER JOIN participants on s.id::varchar(20) = participants.scorecard_uuid\n      WHERE \n        s.program_id in (${program_id})\n        AND $__timeFilter(s.conducted_date)\n        AND s.scorecard_type in ($scorecard_type)\n        AND s.year in ($year)\n        AND s.facility_id in ($facility_id)\n        AND s.province_id in ($province_id)\n        AND s.local_ngo_id in ($local_ngo_id)\n        AND s.deleted_at is null\n        AND participants.age BETWEEN ${age:raw}\n        AND participants.gender in ($gender)\n      group by s.id\n    ) as sc\n  WHERE string_to_array(sc.profile, ', ') && array[$profile]\n)\n\nSELECT\n  tm.name,\n  sum(tm.total_planned) as \"ចំនួនគ្រោងទុក\",\n  sum(tm.total_conducted) as \"ចំនួនបានអនុវត្ត\"\nFROM (\n  SELECT\n    facilities.name_km as name,\n    \n    (\n      SELECT count(*)\n      FROM scorecards as s1\n      WHERE\n        s1.program_id in (${program_id})\n        AND $__timeFilter(s1.created_at)\n        AND s1.scorecard_type in ($scorecard_type)\n        AND s1.year in ($year)\n        AND s1.facility_id = facilities.id\n        AND s1.province_id in ($province_id)\n        AND s1.local_ngo_id in ($local_ngo_id)\n        AND s1.deleted_at is null\n    ) AS \"total_planned\",\n\n    COUNT(CASE WHEN filtered_scorecards.locked_at is not null THEN 1 END) as \"total_conducted\"\n  FROM filtered_scorecards\n  INNER JOIN facilities ON filtered_scorecards.facility_id = facilities.id\n  GROUP BY facilities.name_km, facilities.id\n) AS tm\nGROUP BY tm.name;"
    }
   ]
  },
  {
   "title": "លក្ខណៈវិនិច្ឆ័យដែលស្នើឡើងច្រើនជាងគេទាំង៥",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "rawSql": "WITH pa AS (\n  SELECT\n    p.*,\n    concat_ws (\n      ', ',\n      (CASE WHEN p.disability = true THEN 'Disability' END),\n      (CASE WHEN p.minority = true THEN 'Minority' END),\n      (CASE WHEN p.youth = true THEN 'Youth' END),\n      (CASE WHEN p.poor_card = true THEN 'ID Poor' END),\n      (CASE WHEN (p.disability = false AND p.minority = false AND p.youth = false AND p.poor_card = false) THEN 'N/A' END)\n    ) as profile\n  FROM participants AS p\n),\nraised AS (\n  SELECT\n    pa.*,\n    raised_indicators.id,\n    raised_indicators.indicatorable_id,\n    raised_indicators.indicatorable_type\n  FROM pa\n  INNER JOIN raised_indicators ON pa.uuid = raised_indicators.participant_uuid\n  WHERE\n    string_to_array(pa.profile, ', ') && array[$profile]\n    AND pa.gender in ($gender)\n    AND pa.age BETWEEN ${age:raw}\n),\nindi AS (\n  SELECT id, name, 'Indicator' as type FROM indicators\n  UNION ALL\n  SELECT id, name, 'CustomIndicator' as type FROM custom_indicators\n)\n\nSELECT\n  indi.name,\n  count(*) as \"ចំនួនស្នើឡើង\"\nFROM raised\nINNER JOIN scorecards ON\n  raised.scorecard_uuid::INTEGER = scorecards.id\nINNER JOIN indi ON\n  raised.indicatorable_id = indi.id\n  AND raised.indicatorable_type = indi.type\nWHERE \n  scorecards.program_id in (${program_id})\n  AND $__timeFilter(scorecards.conducted_date)\n  AND scorecards.scorecard_type in ($scorecard_type)\n  AND scorecards.year in ($year)\n  AND scorecards.facility_id in ($facility_id)\n  AND scorecards.province_id in ($province_id)\n  AND scorecards.local_ngo_id in ($local_ngo_id)\n  AND scorecards.deleted_at is null\nGROUP BY indi.name\nORDER BY \"ចំនួនស្នើឡើង\" DESC\nLIMIT 5;"
    }
   ]
  },
  {
   "title": "លក្ខណៈវិនិច្ឆ័យដែលបានអនុវត្តច្រើនជាងគេទាំង៥",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "rawSql": "WITH pa AS (\n  SELECT\n    p.*,\n    concat_ws (\n      ', ',\n      (CASE WHEN p.disability = true THEN 'Disability' END),\n      (CASE WHEN p.minority = true THEN 'Minority' END),\n      (CASE WHEN p.youth = true THEN 'Youth' END),\n      (CASE WHEN p.poor_card = true THEN 'ID Poor' END),\n      (CASE WHEN (p.disability = false AND p.minority = false AND p.youth = false AND p.poor_card = false) THEN 'N/A' END)\n    ) as profile\n  FROM participants AS p\n),\nraised AS (\n  SELECT\n    pa.*,\n    raised_indicators.id,\n    raised_indicators.indicatorable_id,\n    raised_indicators.indicatorable_type,\n    raised_indicators.selected\n  FROM pa\n  INNER JOIN raised_indicators ON pa.uuid = raised_indicators.participant_uuid\n  WHERE\n    string_to_array(pa.profile, ', ') && array[$profile]\n    AND pa.gender in ($gender)\n    AND pa.age BETWEEN ${age:raw}\n),\nindi AS (\n  SELECT id, name, 'Indicator' as type FROM indicators\n  UNION ALL\n  SELECT id, name, 'CustomIndicator' as type FROM custom_indicators\n)\n\nSELECT\n  indi.name,\n  count(nullif(raised.selected = false, true)) as \"ចំនួនជ្រើសរើស\"\nFROM raised\nINNER JOIN scorecards ON\n  raised.scorecard_uuid::INTEGER = scorecards.id\nINNER JOIN indi ON\n  raised.indicatorable_id = indi.id\n  AND raised.indicatorable_type = indi.type\nWHERE \n  scorecards.program_id in ($program_id)\n  AND $__timeFilter(scorecards.conducted_date)\n  AND scorecards.scorecard_type in ($scorecard_type)\n  AND scorecards.year in ($year)\n  AND scorecards.facility_id in ($facility_id)\n  AND scorecards.province_id in ($province_id)\n  AND scorecards.local_ngo_id in ($local_ngo_id)\n  AND scorecards.deleted_at is null\nGROUP BY indi.name\nHAVING count(nullif(raised.selected = false, true)) > 0\nORDER BY \"ចំនួនជ្រើសរើស\" DESC\nLIMIT 5;"
    }
   ]
  },
  {
   "title": "លក្ខណៈវិនិច្ឆ័យអាទិភាពទាំង៥ (ពេញចិត្ត)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 33 },
   "targets": [
    {
     "rawSql": "WITH pa AS (\n  SELECT\n    p.*,\n    concat_ws (\n      ', ',\n      (CASE WHEN p.disability = true THEN 'Disability' END),\n      (CASE WHEN p.minority = true THEN 'Minority' END),\n      (CASE WHEN p.youth = true THEN 'Youth' END),\n      (CASE WHEN p.poor_card = true THEN 'ID Poor' END),\n      (CASE WHEN (p.disability = false AND p.minority = false AND p.youth = false AND p.poor_card = false) THEN 'N/A' END)\n    ) as profile\n  FROM participants AS p\n),\nrate AS (\n  SELECT\n    pa.*,\n    ratings.score,\n    ratings.voting_indicator_uuid,\n    ratings.participant_uuid\n  FROM pa\n  INNER JOIN ratings ON pa.uuid = ratings.participant_uuid\n  WHERE\n    string_to_array(pa.profile, ', ') && array[$profile]\n    AND pa.gender in ($gender)\n    AND pa.age BETWEEN ${age:raw}\n    AND ratings.score > 3\n),\nindi AS (\n  SELECT id, name, 'Indicator' as type FROM indicators\n  UNION ALL\n  SELECT id, name, 'CustomIndicator' as type FROM custom_indicators\n)\n\nSELECT\n  indi.name,\n  count(*) as \"ចំនួនបោះឆ្នោត\"\nFROM rate\nINNER JOIN voting_indicators\n  ON voting_indicators.uuid = rate.voting_indicator_uuid\nINNER JOIN indi\n  ON voting_indicators.indicatorable_id = indi.id\n  AND voting_indicators.indicatorable_type = indi.type\nINNER JOIN scorecards ON\n  voting_indicators.scorecard_uuid::INTEGER = scorecards.id\nWHERE\n  scorecards.program_id in (${program_id})\n  AND $__timeFilter(scorecards.conducted_date)  \n  AND scorecards.scorecard_type in ($scorecard_type) \n  AND scorecards.year in ($year) \n  AND scorecards.facility_id in ($facility_id)\n  AND scorecards.province_id in ($province_id)\n  AND scorecards.local_ngo_id in ($local_ngo_id)\n  AND scorecards.deleted_at is null\nGROUP BY indi.name\nORDER BY \"ចំនួនបោះឆ្នោត\" DESC\nLIMIT 5;\n"
    }
   ]
  },
  {
   "title": "លក្ខណៈវិនិច្ឆ័យអាទិភាពទាំង៥ (ទទួលយកបាន)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 33 },
   "targets": [
    {
     "rawSql": "WITH pa AS (\n  SELECT\n    p.*,\n    concat_ws (\n      ', ',\n      (CASE WHEN p.disability = true THEN 'Disability' END),\n      (CASE WHEN p.minority = true THEN 'Minority' END),\n      (CASE WHEN p.youth = true THEN 'Youth' END),\n      (CASE WHEN p.poor_card = true THEN 'ID Poor' END),\n      (CASE WHEN (p.disability = false AND p.minority = false AND p.youth = false AND p.poor_card = false) THEN 'N/A' END)\n    ) as profile\n  FROM participants AS p\n),\nrate AS (\n  SELECT\n    pa.*,\n    ratings.score,\n    ratings.voting_indicator_uuid,\n    ratings.participant_uuid\n  FROM pa\n  INNER JOIN ratings ON pa.uuid = ratings.participant_uuid\n  WHERE\n    string_to_array(pa.profile, ', ') && array[$profile]\n    AND pa.gender in ($gender)\n    AND pa.age BETWEEN ${age:raw}\n    AND ratings.score = 3\n),\nindi AS (\n  SELECT id, name, 'Indicator' as type FROM indicators\n  UNION ALL\n  SELECT id, name, 'CustomIndicator' as type FROM custom_indicators\n)\n\nSELECT\n  indi.name,\n  count(*) as \"ចំនួនបោះឆ្នោត\"\nFROM rate\nINNER JOIN voting_indicators\n  ON voting_indicators.uuid = rate.voting_indicator_uuid\nINNER JOIN indi\n  ON voting_indicators.indicatorable_id = indi.id\n  AND voting_indicators.indicatorable_type = indi.type\nINNER JOIN scorecards ON\n  voting_indicators.scorecard_uuid::INTEGER = scorecards.id\nWHERE\n  scorecards.program_id in (${program_id})\n  AND $__timeFilter(scorecards.conducted_date)  \n  AND scorecards.scorecard_type in ($scorecard_type) \n  AND scorecards.year in ($year) \n  AND scorecards.facility_id in ($facility_id)\n  AND scorecards.province_id in ($province_id)\n  AND scorecards.local_ngo_id in ($local_ngo_id)\n  AND scorecards.deleted_at is null\nGROUP BY indi.name\nORDER BY \"ចំនួនបោះឆ្នោត\" DESC\nLIMIT 5;\n"
    }
   ]
  },
  {
   "title": "លក្ខណៈវិនិច្ឆ័យអាទិភាពទាំង៥ (មិនពេញចិត្ត)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 33 },
   "targets": [
    {
     "rawSql": "WITH pa AS (\n  SELECT\n    p.*,\n    concat_ws (\n      ', ',\n      (CASE WHEN p.disability = true THEN 'Disability' END),\n      (CASE WHEN p.minority = true THEN 'Minority' END),\n      (CASE WHEN p.youth = true THEN 'Youth' END),\n      (CASE WHEN p.poor_card = true THEN 'ID Poor' END),\n      (CASE WHEN (p.disability = false AND p.minority = false AND p.youth = false AND p.poor_card = false) THEN 'N/A' END)\n    ) as profile\n  FROM participants AS p\n),\nrate AS (\n  SELECT\n    pa.*,\n    ratings.score,\n    ratings.voting_indicator_uuid,\n    ratings.participant_uuid\n  FROM pa\n  INNER JOIN ratings ON pa.uuid = ratings.participant_uuid\n  WHERE\n    string_to_array(pa.profile, ', ') && array[$profile]\n    AND pa.gender in ($gender)\n    AND pa.age BETWEEN ${age:raw}\n    AND ratings.score < 3\n),\nindi AS (\n  SELECT id, name, 'Indicator' as type FROM indicators\n  UNION ALL\n  SELECT id, name, 'CustomIndicator' as type FROM custom_indicators\n)\n\nSELECT\n  indi.name,\n  count(*) as \"ចំនួនបោះឆ្នោត\"\nFROM rate\nINNER JOIN voting_indicators\n  ON voting_indicators.uuid = rate.voting_indicator_uuid\nINNER JOIN indi\n  ON voting_indicators.indicatorable_id = indi.id\n  AND voting_indicators.indicatorable_type = indi.type\nINNER JOIN scorecards ON\n  voting_indicators.scorecard_uuid::INTEGER = scorecards.id\nWHERE\n  scorecards.program_id in (${program_id})\n  AND $__timeFilter(scorecards.conducted_date)  \n  AND scorecards.scorecard_type in ($scorecard_type) \n  AND scorecards.year in ($year) \n  AND scorecards.facility_id in ($facility_id)\n  AND scorecards.province_id in ($province_id)\n  AND scorecards.local_ngo_id in ($local_ngo_id)\n  AND scorecards.deleted_at is null\nGROUP BY indi.name\nORDER BY \"ចំនួនបោះឆ្នោត\" DESC\nLIMIT 5;\n"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 23, "x": 1, "y": 41 },
   "options": {
    "content": "<div style=\"display: flex;\">\n<div style=\"display: flex;margin: 0 auto;\">\n<div style=\"text-align: center; margin-right: 20px\">\n<h5 style=\"font-size: 14px;\">គាំទ្រមូលនិធិដោយ/Funded by</h5>\n<img src=\"https://digital-csc.org/assets/eu-3902d24e7e972494ede15c7dc533bc20589ef6e80aca3335518cea5944984c09.png\"  width=\"70\"/>\n</div>\n\n<div style=\"text-align: center\">\n<h5 style=\"font-size: 14px;\">អនុវត្តដោយ/Implemented by</h5>\n<div style=\"display: flex; align-items: center; justify-content: center; margin-top: 30px;\">\n<img src=\"https://digital-csc.org/assets/care_logo-30bc7807ccb532ee750d35b55a3e94c40e688a88a18d0497c4e244bc56f4017d.png\" width=\"130\" height=\"40\" />\n<img src=\"https://digital-csc.org/assets/api-a84a9246854e6e9c471aa6982fb90ed27377b050f69318966fe0c3923d371886.png\"  width=\"55\" style=\"margin: 0 20px;\"/>\n<img src=\"https://digital-csc.org/assets/instedd-ilabsea-252db350ccbce84ff56c4057db2f6a5761873c8d7b4c9c5ee9c31049ba7d3792.png\"  width=\"180\"/>\n</div>\n</div>\n\n</div>\n</div>\n  \n<div style=\"text-align: center; padding-top: 20px; padding-bottom: 20px;\">\n  <a href=\"https://digital-csc.org/\" target=\"_blank\" >អំពីយើង/About Us</a>\n</div>\n  "
   },
   "targets": [
    {
     "rawSql": "SELECT\n  created_at AS \"time\",\n  latitude\nFROM locations\nWHERE\n  $__timeFilter(created_at)\nORDER BY 1"
    }
   ]
  }
 ]
}